extends:
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:prettier/recommended # last

plugins:
  - prettier
  - import

parser: babel-eslint

parserOptions:
  ecmaVersion: 2019
  sourceType: module

rules:
  # --- defaults ---

  # prettier: some rules are kept for reference but commented out to avoid
  #   conflicts with prettier

  no-console: warn
  no-debugger: warn
  no-floating-decimal: off
  no-mixed-operators: off
  no-return-assign: off
  no-self-compare: error
  no-trailing-spaces: warn
  no-unused-vars: [warn, { args: after-used }]
  no-tabs: off
  no-var: warn
  # operator-linebreak: [warn, before, overrides: { =: after }] # prettier
  padded-blocks: off
  prefer-const: warn
  # quotes: [warn, single, {avoidEscape: true}] # prettier
  indent: [off, 2]
  space-before-function-paren: off
  space-before-blocks: off
  template-curly-spacing: off # fails on ${'' /* comment */}

  # --- import---

  import/first: off
  import/no-named-as-default: off
